version: '3'
services:
  rabbitmq:
    container_name: 'rabbitmq'
    build:
      context: ./
      dockerfile: ./image/Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - somenetwork

networks:
  somenetwork:
    driver: bridge